import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import sparkleIcon from "@/components/SparkleIcon";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const captioniser ='Subtracktor'
  return (
    <html lang="en">
      <body className={inter.className+
        " bg-gradient-to-b  from-bg-gradient-from to-bg-gradient-to min-h-screen text-white"}>
        <main className="p-4 max-w-2xl mx-auto">
        <header className="flex justify-between my-2 sm:my-8 text-[#ddf0ed]">
        <Link href="/" className="flex gap-1">
        {sparkleIcon()}
        <span>{captioniser}</span>
        </Link>
        <nav className="flex items-center gap-2 sm:gap-6 text-[#ddf0ed]/80 text-sm sm:text-lg">
          <Link href="/">Home</Link>
          <Link href="/pricing">Pricing</Link>
          <a href="mailto:contact@epiCaptions.com">Contact</a>
        </nav>
      </header>
        {children}
        </main>
        </body>
    </html>
  );
}
